{
 "title": "Kafka",
 "time": { "from": "now-12m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Kafka KPIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of incoming message per sec - one min rate",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "servers.*.MessagesInPerSec.OneMinuteRate"
    }
   ]
  },
  {
   "title": "Number of incoming bytes last minute in entire cluster",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "servers.*.BytesInPerSec.OneMinuteRate"
    }
   ]
  },
  {
   "title": "Request queue size",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "servers.*.RequestQueueSize.Value"
    }
   ]
  },
  { "title": "System KPIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "collectd - memory used in %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "collectd.server-x.memory.percent-used"
    },
    {
     "target": "collectd.server-x.memory.percent-used"
    },
    {
     "target": "collectd.server-x_de.memory.percent-used"
    }
   ]
  },
  {
   "title": "collectd - load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "collectd.server-x.load.load.shortterm"
    },
    {
     "target": "collectd.server-x.load.load.shortterm"
    },
    {
     "target": "collectd.server-x_de.load.load.shortterm"
    }
   ]
  },
  {
   "title": "collectd - packages received per second on eth0",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "collectd.server-x.interface-eth0.if_packets.rx"
    },
    {
     "target": "collectd.server-x.interface-eth0.if_packets.rx"
    },
    {
     "target": "collectd.server-x_de.interface-eth0.if_packets.rx"
    }
   ]
  },
  {
   "title": "collectd - packages transmitted per second on eth0",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "collectd.server-x.interface-eth0.if_packets.tx"
    },
    {
     "target": "collectd.server-x.interface-eth0.if_packets.tx"
    },
    {
     "target": "collectd.server-x_de.interface-eth0.if_packets.tx"
    }
   ]
  },
  {
   "title": "JVM - Heap Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "servers.server-x.jvmMemory.HeapMemoryUsage_committed"
    },
    {
     "target": "servers.server-x.jvmMemory.HeapMemoryUsage_init"
    },
    {
     "target": "servers.server-x.jvmMemory.HeapMemoryUsage_max"
    },
    {
     "target": "servers.server-x.jvmMemory.HeapMemoryUsage_used"
    }
   ]
  },
  {
   "title": "JVM - Non-Heap Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "servers.server-x.jvmMemory.NonHeapMemoryUsage_committed"
    },
    {
     "target": "servers.server-x.jvmMemory.NonHeapMemoryUsage_init"
    },
    {
     "target": "servers.server-x.jvmMemory.NonHeapMemoryUsage_max"
    },
    {
     "target": "servers.server-x.jvmMemory.NonHeapMemoryUsage_used"
    }
   ]
  }
 ]
}